# Generated by Django 5.2 on 2025-08-08 04:13

import games.validators
import lrgnetwork.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=lrgnetwork.storage_backends.MediaStorage,
                upload_to="game_logos/",
                validators=[games.validators.validate_image],
            ),
        ),
        migrations.AlterField(
            model_name="gameimages",
            name="image",
            field=models.ImageField(
                storage=lrgnetwork.storage_backends.MediaStorage,
                upload_to="game_images/",
                validators=[games.validators.validate_image],
            ),
        ),
    ]
