# Generated by Django 5.1.13 on 2025-10-06 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_alter_game_logo_alter_gameimages_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="instagram_hanlde",
            new_name="instagram_handle",
        ),
    ]
