# Generated by Django 5.1.13 on 2025-10-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_rename_instagram_hanlde_game_instagram_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="facebook_link",
            field=models.CharField(
                blank=True,
                help_text="Enter just the page name (e.g. www.facebook.com/<b>pagename</b>)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="instagram_handle",
            field=models.CharField(
                blank=True,
                help_text="Enter just the handle (e.g. www.instagram.com/<b>handle</b>)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="lrg_wiki_page",
            field=models.CharField(
                blank=True,
                help_text="Enter just the page name (e.g. https://live-reality-games.fandom.com/wiki/<b>Page_Name</b>)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="youtube_link",
            field=models.CharField(
                blank=True,
                help_text="Enter any valid youtube link (e.g. www.youtube.com/<b>channelname</b>",
                max_length=200,
                null=True,
            ),
        ),
    ]
