# Generated by Django 5.1.8 on 2025-04-25 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("games", "0003_remove_game_updated_by_remove_gamedate_updated_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.city",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="cities_light.region",
            ),
        ),
    ]
