# Generated by Django 5.2 on 2025-04-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0003_remove_game_updated_by_remove_gamedate_updated_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
