# Generated by Django 5.1.13 on 2025-10-06 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cities_light", "0011_alter_city_country_alter_city_region_and_more"),
        ("games", "0004_alter_game_facebook_link_alter_game_instagram_handle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="game",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_removed", False)),
                fields=("slug",),
                name="unique_slug_for_active_games",
            ),
        ),
    ]
