# Generated by Django 5.2 on 2025-05-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0004_game_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="game_logos/"),
        ),
    ]
