# Generated by Django 5.2 on 2025-05-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_game_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_format",
            field=models.CharField(
                choices=[
                    ("AR", "Amazing Race"),
                    ("BB", "Big Brother"),
                    ("SU", "Survivor"),
                    ("TM", "Task Master"),
                    ("CH", "The Challenge"),
                    ("MO", "The Mole"),
                    ("TR", "The Traitors"),
                    ("OF", "Original Format"),
                ],
                max_length=2,
            ),
        ),
    ]
