# Generated by Django 5.1.13 on 2025-10-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0005_alter_game_slug_game_unique_slug_for_active_games"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="youtube_link",
            field=models.CharField(
                blank=True,
                help_text="Enter any valid youtube path (e.g. www.youtube.com/<b>channelname</b>)",
                max_length=200,
                null=True,
            ),
        ),
    ]
