# Generated by Django 5.1.13 on 2025-10-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_game_youtube_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="game_format",
            field=models.CharField(
                choices=[
                    ("AR", "Amazing Race"),
                    ("BB", "Big Brother"),
                    ("GG", "Genius Games"),
                    ("SU", "Survivor"),
                    ("TM", "Task Master"),
                    ("CH", "The Challenge"),
                    ("MO", "The Mole"),
                    ("TR", "The Traitors"),
                    ("OF", "Original Format"),
                    ("VF", "Various Formats"),
                ],
                max_length=2,
            ),
        ),
    ]
