# Generated by Django 5.2 on 2025-05-20 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0006_alter_game_game_format"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="number_of_days",
        ),
    ]
