# Generated by Django 5.1.13 on 2025-11-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0007_alter_game_game_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="discord_link",
            field=models.CharField(
                blank=True,
                help_text="Enter just the part after discord.gg/ (e.g. https://discord.gg/<b>invitecode</b>)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="tiktok_handle",
            field=models.CharField(
                blank=True,
                help_text="Enter just the username (e.g. https://www.tiktok.com/@<b>username</b>)",
                max_length=200,
                null=True,
            ),
        ),
    ]
